# Generated by Django 3.2.16 on 2023-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='文件名')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'files_storage',
                'ordering': ['-id'],
            },
        ),
    ]
